# Synthelion — Python port of Caveman (https://github.com/francescopaolopassaro/caveman)
# © 2026 Passaro Francesco Paolo — Digitalsolutions.it
from __future__ import annotations

import hashlib
import logging
import math
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass
from threading import Lock
from typing import Callable

import regex

_log = logging.getLogger(__name__)

from synthelion import cjk_segmenter
from synthelion.detector import LanguageDetector
from synthelion.models import CompressionLevel, CompressionResult
from synthelion.word_provider import FunctionWordProvider

# Ported from Caveman C# 1.4.1: \w in Python's stdlib `re` (like \p{L} in .NET) does not
# include combining marks (Unicode category M*), so a regex-only tokenizer fragments words
# in scripts that attach vowel signs/virama as separate codepoints (Kannada, Hindi, Tamil,
# Thai, ...) — e.g. "दिन" split into "द" and "न". `regex` (already a declared dependency)
# supports \p{...} Unicode property escapes directly, exactly like the C# fix, and is a
# compiled matcher rather than a per-character Python loop — the same correctness fix without
# a performance regression.
_WORD_SPLIT = regex.compile(
    r"[\p{L}\p{M}\p{N}_]+(?:'[\p{L}\p{M}\p{N}_]+)?|[^\w\s]", regex.UNICODE
)

# Languages that capitalise all common nouns — the positional proper-noun
# heuristic is disabled for these (same as C# CapitalizedNounLanguages).
_CAPITALIZED_NOUN_LANGS = frozenset({"deu"})

# Language group → suffix lists (ported from C# IsDescriptiveWord).
# "al"/"ical" (English) and "are" (Romance) were removed in Caveman C# 1.4.1: they catch
# genuinely decorative adjectives ("occasional") or, for "are", nothing but adjectives in
# theory — but "are" also matches EVERY Italian first-conjugation infinitive verb
# ("analizzare", "parlare"), and "al"/"ical" just as often match a domain-specifying
# adjective that IS the information ("financial"/"medical"/"legal" report are not
# interchangeable). A comprehensibility test suite caught both dropping real content
# (a sentence's main verb, and "financial" from "quarterly financial report"). Losing real
# content outweighs catching a few filler adjectives, so both stay out here too.
_EN_ADV = ("ly", "wise", "wards")
_EN_ADJ = ("ous", "ive", "able", "ible", "ful", "less", "ic", "ant", "ent", "ish", "like", "some")
_ROMANCE_ADV = ("mente",)
_ROMANCE_ADJ = ("oso", "osa", "ivo", "iva", "abile", "ibile", "ale", "ese", "ista")
_GERMANIC_ADJ = ("lich", "ig", "isch", "sam", "bar", "haft", "los", "voll", "arm", "reich")
_SLAVIC_ADJ = ("ный", "ная", "ное", "ные", "ний", "ня", "нє", "ова", "еви", "ски", "цки", "скиј", "чки")


def _lang_group(iso3: str) -> str:
    return {
        "eng": "en",
        "ita": "romance", "fra": "romance", "spa": "romance", "por": "romance",
        "ron": "romance", "cat": "romance", "glg": "romance", "lat": "romance",
        "deu": "germanic", "nld": "germanic", "afr": "germanic",
        "swe": "germanic", "dan": "germanic", "nor": "germanic", "isl": "germanic",
        "rus": "slavic", "ukr": "slavic", "bel": "slavic", "bul": "slavic",
        "srp": "slavic", "hrv": "slavic", "slv": "slavic", "slk": "slavic",
        "ces": "slavic", "pol": "slavic", "mkd": "slavic",
        "ara": "semitic", "heb": "semitic", "fas": "semitic", "urd": "semitic",
        "hin": "indic", "ben": "indic", "mar": "indic", "tel": "indic",
        "tam": "indic", "kan": "indic",
        "zho": "east_asian", "jpn": "east_asian", "kor": "east_asian",
        "tha": "east_asian", "vie": "east_asian",
        "tur": "uralic_altaic", "kaz": "uralic_altaic", "fin": "uralic_altaic",
        "est": "uralic_altaic", "hun": "uralic_altaic", "hye": "uralic_altaic",
        "ell": "uralic_altaic",
    }.get(iso3.lower(), "other")


def _is_descriptive(word: str, group: str) -> bool:
    if len(word) < 4:
        return False
    w = word.lower()
    if group == "en":
        return any(w.endswith(s) and len(w) > len(s) + 1 for s in _EN_ADV) or \
               any(w.endswith(s) and len(w) > len(s) + 2 for s in _EN_ADJ)
    if group == "romance":
        if w.endswith("mente") and len(w) > 7:
            return True
        return any(w.endswith(s) and len(w) > len(s) + 2 for s in _ROMANCE_ADJ)
    if group == "germanic":
        return any(w.endswith(s) and len(w) > len(s) + 2 for s in _GERMANIC_ADJ)
    if group == "slavic":
        return any(w.endswith(s) and len(w) > len(s) + 2 for s in _SLAVIC_ADJ)
    if group == "semitic":
        return len(w) > 5 and (w.startswith("al") or w.startswith("el"))
    if group == "uralic_altaic":
        return any(w.endswith(s) for s in ("лар", "лер", "дар", "дер", "тар", "тер", "мен", "бен", "пен"))
    return False


def _is_number(token: str) -> bool:
    return all(c.isdigit() or c in ".,- " for c in token) and bool(token)


# Generic words are now loaded per-iso3 from {iso3}.generic.yaml.br files
# (generated by scripts/generate_worddata.py). No hardcoded word lists here.
_GENERIC_FALLBACK: frozenset[str] = frozenset({
    "time", "day", "year", "person", "thing", "place", "world", "life",
    "big", "small", "new", "old", "good", "bad",
    "now", "then", "today", "yesterday", "tomorrow", "always", "never",
})

# Sentence-ending punctuation: splits the token stream into pseudo-documents for TF-IDF
# (STATISTICAL) and into clauses for verb detection (SYNTACTIC). Ported from Caveman C# 1.4.1.
_SENTENCE_ENDERS = frozenset({".", "!", "?", "…"})

# Negation particles are grammatically function words (curated per-language word lists
# correctly classify them as such) but semantically load-bearing — dropping "non"/"not"
# doesn't just cost fluency, it silently inverts the sentence's meaning ("non c'era
# sensibilità" -> "c'era sensibilità"). Found via a real compressed-text review: Italian
# "non" was being stripped at every level. A small closed set per language (this is a
# fixed grammatical category, unlike open-ended function-word/lemma dictionaries, so a
# short in-code list here is the same kind of exception as _SENTENCE_ENDERS or the
# adjective-suffix lists above, not a "hardcoded dictionary"). Matched case-insensitively
# against the raw surface form, never lemmatised.
_NEGATION_WORDS: dict[str, frozenset[str]] = {
    "eng": frozenset({"not", "n't", "no", "never", "none", "nobody", "nothing", "neither", "nor"}),
    "ita": frozenset({"non", "no", "né", "neanche", "nemmeno", "manco"}),
    "fra": frozenset({"ne", "pas", "non", "jamais", "aucun", "aucune", "rien", "personne"}),
    "spa": frozenset({"no", "nunca", "jamás", "ni", "nadie", "nada", "ningún", "ninguna", "ninguno"}),
    "deu": frozenset({"nicht", "kein", "keine", "keiner", "keinem", "keinen", "keines", "nie", "niemals", "nichts", "niemand"}),
    "por": frozenset({"não", "nao", "nunca", "jamais", "nem", "nenhum", "nenhuma", "ninguém"}),
    "zho": frozenset({"不", "没", "没有", "别", "无", "非", "未", "莫"}),
}


# Languages where negation is a bound prefix morpheme rather than a separate word:
# Chinese's dictionary-based segmenter (cjk_segmenter) legitimately merges "不" + the
# verb/adjective it negates into one word when that compound is itself in the
# vocabulary ("不是", "不管", "不过", ...) -- an exact-match check against
# _NEGATION_WORDS never matches those compounds, so the whole token gets treated as
# an ordinary function word and stripped, silently losing the negation (found via
# real-text testing: "这不是我们的问题" dropped "不是" entirely at every level).
_NEGATION_PREFIX_LANGS = frozenset({"zho"})


def _is_negation(word: str, iso3: str) -> bool:
    lower = word.lower()
    neg = _NEGATION_WORDS.get(iso3.lower(), frozenset())
    if lower in neg:
        return True
    if iso3.lower() in _NEGATION_PREFIX_LANGS:
        return any(lower.startswith(p) for p in neg)
    return False


@dataclass
class CompressionFilter:
    keep_only: set[str] | None = None  # categories: FUNC, PUNCT, NUM, PROPN, CONTENT
    remove: set[str] | None = None
    custom_predicate: Callable[[str], bool] | None = None


def _categorize(word: str, fw: frozenset[str]) -> str:
    if word.lower() in fw:
        return "FUNC"
    if _is_number(word):
        return "NUM"
    if word and word[0].isupper() and len(word) > 1:
        return "PROPN"
    return "CONTENT"


_CACHE_TTL = 1800   # 30 minutes — matches ContentRouter's cache for consistency
_CACHE_MAX = 512    # max entries — evict oldest 25% when full


class CompressionService:
    """NLP prompt compressor: strips function words and lemmatizes tokens.

    Ported from C# CavemanCompressionService. Supports Light, Semantic and
    Aggressive compression levels across 50+ languages. Zero ML model dependency.
    """

    def __init__(
        self,
        word_provider: FunctionWordProvider | None = None,
        detector: LanguageDetector | None = None,
    ) -> None:
        self._provider = word_provider or FunctionWordProvider()
        self._detector = detector or LanguageDetector(self._provider)
        # Same hash→result/TTL/eviction pattern as ContentRouter.route() — repeated
        # identical calls (e.g. the same system prompt compressed every turn) skip
        # re-tokenizing/re-lemmatizing entirely. Keyed on (text, level, iso3): the
        # exact inputs apply_compression() is a pure function of.
        self._cache: dict[str, tuple[CompressionResult, float]] = {}
        self._cache_lock = Lock()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def detect_language(self, text: str) -> str:
        return self._detector.detect(text)

    def detect_language_scores(self, text: str) -> dict[str, float]:
        return self._detector.detect_with_scores(text)

    def compress(
        self,
        text: str,
        level: CompressionLevel = CompressionLevel.SEMANTIC,
        iso3: str | None = None,
        custom_filter: CompressionFilter | None = None,
    ) -> CompressionResult:
        if not text or not text.strip():
            return CompressionResult(compressed_text="")

        # custom_filter is an arbitrary caller-supplied callable — not guaranteed
        # deterministic or safely reusable across calls, so it bypasses the cache
        # entirely rather than risk serving a stale result for a filter that behaves
        # differently call to call.
        cache_key = None
        if custom_filter is None:
            cache_key = hashlib.md5(f"{text}\x00{level}\x00{iso3 or ''}".encode()).hexdigest()
            with self._cache_lock:
                entry = self._cache.get(cache_key)
                if entry and time.time() - entry[1] < _CACHE_TTL:
                    return entry[0]

        try:
            lang = iso3 or self._detector.detect(text)
            result = self.apply_compression(text, lang, level, custom_filter)
        except Exception as exc:
            _log.warning("compress() failed: %s", exc, exc_info=True)
            return CompressionResult(compressed_text=text, error_message=str(exc))

        if cache_key is not None:
            with self._cache_lock:
                self._cache[cache_key] = (result, time.time())
                if len(self._cache) > _CACHE_MAX:
                    # Evict oldest 25% of entries
                    sorted_keys = sorted(self._cache, key=lambda k: self._cache[k][1])
                    for k in sorted_keys[: _CACHE_MAX // 4]:
                        del self._cache[k]

        return result

    def compress_batch(
        self,
        texts: list[str],
        level: CompressionLevel = CompressionLevel.SEMANTIC,
        max_workers: int = 4,
    ) -> list[CompressionResult]:
        """Compress a list of texts, using threads for batches larger than 8."""
        if len(texts) <= 8:
            return [self.compress(t, level) for t in texts]
        results: list[CompressionResult | None] = [None] * len(texts)
        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            futures = {ex.submit(self.compress, t, level): i for i, t in enumerate(texts)}
            for fut in as_completed(futures):
                results[futures[fut]] = fut.result()
        return results  # type: ignore[return-value]

    def apply_compression(
        self,
        text: str,
        iso3: str,
        level: CompressionLevel,
        custom_filter: CompressionFilter | None = None,
    ) -> CompressionResult:
        if not text or not text.strip():
            return CompressionResult(compressed_text="")

        fw = self._provider.get_function_words(iso3)
        lemmas = self._provider.get_lemma_map(iso3)
        proper_nouns = self._provider.get_proper_nouns(iso3)
        # Loaded (and cached by the provider) for every level, not just SYNTACTIC: also
        # guards _lemma_or_lower against ADV-tagged homograph-contaminated lemma entries
        # (e.g. Italian "subito" wrongly lemmatised to "subire") at every compression level.
        pos_tags = self._provider.get_pos_tags(iso3)

        tokens = _tokenize(text)
        original_count = len(tokens)

        if level == CompressionLevel.NONE and custom_filter is None:
            return CompressionResult(
                compressed_text=text,
                original_tokens=original_count,
                compressed_tokens=original_count,
            )

        if custom_filter is not None:
            filtered = _apply_custom(tokens, fw, custom_filter)
        elif level == CompressionLevel.LIGHT:
            filtered = _filter_light(tokens, fw, iso3)
        elif level == CompressionLevel.SEMANTIC:
            filtered = _filter_semantic(tokens, fw, lemmas, proper_nouns, iso3, pos_tags)
        elif level == CompressionLevel.AGGRESSIVE:
            generic = self._provider.get_generic_words(iso3) or _GENERIC_FALLBACK
            filtered = _filter_aggressive(tokens, fw, lemmas, proper_nouns, iso3, generic, pos_tags)
        elif level == CompressionLevel.STATISTICAL:
            generic = self._provider.get_generic_words(iso3) or _GENERIC_FALLBACK
            filtered = _filter_statistical(tokens, fw, lemmas, proper_nouns, iso3, generic, pos_tags)
        else:  # SYNTACTIC
            generic = self._provider.get_generic_words(iso3) or _GENERIC_FALLBACK
            filtered = _filter_syntactic(tokens, fw, lemmas, proper_nouns, iso3, generic, pos_tags)

        compressed = " ".join(filtered)
        return CompressionResult(
            compressed_text=compressed,
            original_tokens=original_count,
            compressed_tokens=len(filtered),
        )


# ------------------------------------------------------------------
# Internal tokenization
# ------------------------------------------------------------------

class _Token:
    __slots__ = ("text", "is_punct")

    def __init__(self, text: str, is_punct: bool) -> None:
        self.text = text
        self.is_punct = is_punct


def _tokenize(text: str) -> list[_Token]:
    tokens = []
    for m in _WORD_SPLIT.finditer(text):
        t = m.group()
        is_punct = not (t[0].isalpha() or t[0].isdigit())
        if not is_punct and len(t) > 1 and cjk_segmenter.is_han(t[0]):
            # Chinese has no spaces between words, so the regex above matched
            # this whole run of Han characters as one "word" -- segment it
            # into real words instead, or every function/negation word check
            # downstream compares against the entire sentence and never matches.
            for word in cjk_segmenter.segment_han_run(t):
                tokens.append(_Token(word, False))
            continue
        tokens.append(_Token(t, is_punct))
    return tokens


# ------------------------------------------------------------------
# Proper-noun (and negation) detection
# ------------------------------------------------------------------

def _detect_proper_nouns(
    tokens: list[_Token],
    iso3: str,
    proper_nouns: frozenset[str],
) -> list[bool]:
    """Returns, per token, whether every filter should keep it verbatim and never
    lemmatise/drop it as a function word. Despite the name this also covers negation
    particles (see _NEGATION_WORDS) — every call site already treats a True here as
    "always keep, unlemmatised", which is exactly what a negation particle needs too,
    so folding it in here means every filter gets the protection for free instead of
    needing its own separate check."""
    cap_noun_lang = iso3.lower() in _CAPITALIZED_NOUN_LANGS
    has_gazetteer = bool(proper_nouns)
    result = [False] * len(tokens)
    sentence_start = True

    for i, tok in enumerate(tokens):
        if tok.is_punct:
            if tok.text in (".", "!", "?", "…"):
                sentence_start = True
            continue
        if _is_negation(tok.text, iso3):
            result[i] = True
            sentence_start = False
            continue
        if tok.text and tok.text[0].isupper():
            in_gazetteer = has_gazetteer and tok.text.lower() in proper_nouns
            if cap_noun_lang:
                result[i] = in_gazetteer
            else:
                result[i] = (not sentence_start) or in_gazetteer
        sentence_start = False

    return result


# ------------------------------------------------------------------
# Compression filters
# ------------------------------------------------------------------

def _filter_light(tokens: list[_Token], fw: frozenset[str], iso3: str) -> list[str]:
    return [
        t.text for t in tokens
        if not t.is_punct and (t.text.lower() not in fw or _is_negation(t.text, iso3))
    ]


def _lemma_or_lower(text: str, lemmas: dict[str, str], pos_tags: dict[str, str] | None = None) -> str:
    lower = text.lower()
    lemma = lemmas.get(lower, lower)
    # Found via real-text review: Italian "subito" (adverb, "immediately") was mapped
    # to "subire" (verb, "to undergo") — the UD-derived lemma map picked the wrong
    # homograph's lemma, same class of bug as "torta"->"torcere" fixed earlier.
    # Adverbs don't meaningfully inflect, so a UD lemma differing from the surface
    # form on an ADV-tagged word is a strong signal of homograph contamination
    # rather than real morphology — skip the substitution rather than trust it.
    if lemma != lower and pos_tags is not None and pos_tags.get(lower) == "ADV":
        return lower
    return lemma


def _filter_semantic(
    tokens: list[_Token],
    fw: frozenset[str],
    lemmas: dict[str, str],
    proper_nouns: frozenset[str],
    iso3: str,
    pos_tags: dict[str, str] | None = None,
) -> list[str]:
    is_proper = _detect_proper_nouns(tokens, iso3, proper_nouns)
    out = []
    for i, tok in enumerate(tokens):
        if tok.is_punct:
            continue
        if is_proper[i]:
            out.append(tok.text)
            continue
        if _is_number(tok.text):
            out.append(tok.text)
            continue
        if tok.text.lower() in fw:
            continue
        normalized = _lemma_or_lower(tok.text, lemmas, pos_tags)
        if normalized in fw:
            continue
        out.append(normalized)
    return out


def _filter_aggressive(
    tokens: list[_Token],
    fw: frozenset[str],
    lemmas: dict[str, str],
    proper_nouns: frozenset[str],
    iso3: str,
    generic: frozenset[str],
    pos_tags: dict[str, str] | None = None,
) -> list[str]:
    # BUGFIX: this function referenced an undefined `group` name (missing the
    # _lang_group(iso3) call below), which raised NameError on every non-trivial
    # sentence — AGGRESSIVE mode was completely broken for any real content word.
    group = _lang_group(iso3)
    is_proper = _detect_proper_nouns(tokens, iso3, proper_nouns)
    out = []

    for i, tok in enumerate(tokens):
        if tok.is_punct:
            continue

        if is_proper[i]:
            out.append(tok.text)
            continue

        if _is_number(tok.text):
            out.append(tok.text)
            continue

        if len(tok.text) <= 1 and not tok.text[0:1].isalpha():
            continue

        lower = tok.text.lower()

        if lower in fw:
            continue

        normalized = _lemma_or_lower(tok.text, lemmas, pos_tags)

        if len(normalized) <= 1:
            continue

        if normalized in fw or normalized in generic:
            continue

        if _is_descriptive(normalized, group):
            continue

        out.append(normalized)

    # Ported from Caveman C# 1.4.1: a short, content-bearing prompt (e.g. a one-word
    # imperative like "Vai."/"Go.") can have its only word classified as generic/
    # descriptive and pruned to nothing. An empty compressed prompt is a total loss of
    # meaning, worse than keeping one extra word, so fall back to the mildest available
    # signal instead of returning nothing.
    if not out and any(not t.is_punct for t in tokens):
        return _filter_semantic(tokens, fw, lemmas, proper_nouns, iso3, pos_tags)

    return out


def _sentence_index_of(tokens: list[_Token]) -> tuple[list[int], int]:
    """Assigns each token its 0-based sentence index; returns (index_per_token, sentence_count)."""
    sentence_of: list[int] = [0] * len(tokens)
    idx = 0
    for i, tok in enumerate(tokens):
        sentence_of[i] = idx
        if tok.is_punct and tok.text in _SENTENCE_ENDERS:
            idx += 1
    return sentence_of, idx + 1


def _filter_statistical(
    tokens: list[_Token],
    fw: frozenset[str],
    lemmas: dict[str, str],
    proper_nouns: frozenset[str],
    iso3: str,
    generic: frozenset[str],
    pos_tags: dict[str, str] | None = None,
) -> list[str]:
    """TF-IDF word scoring instead of curated dictionaries (ported from Caveman C# 1.4.1).

    Scores each distinct word by frequency in the prompt vs. how many of the prompt's
    own sentences contain it, grounding "common" words against the language's curated
    function/generic word lists exactly as a real reference corpus would. Keeps words
    scoring at or above the median of the prompt's own positively-scored vocabulary, so
    the cut is relative to this text rather than a fixed threshold. Never drops a
    sentence to nothing.
    """
    is_proper = _detect_proper_nouns(tokens, iso3, proper_nouns)
    n = len(tokens)
    sentence_of, sentence_count = _sentence_index_of(tokens)

    # Scoring key per token: None for punctuation/proper nouns/numbers.
    # These values are handled separately and never scored away.
    keys: list[str | None] = [None] * n

    for i, tok in enumerate(tokens):
        if tok.is_punct or is_proper[i] or _is_number(tok.text):
            continue

        keys[i] = _lemma_or_lower(tok.text, lemmas, pos_tags)

    term_freq: dict[str, int] = {}
    docs_with_term: dict[str, set[int]] = {}

    for i, key in enumerate(keys):
        if key is None:
            continue

        term_freq[key] = term_freq.get(key, 0) + 1
        docs_with_term.setdefault(key, set()).add(sentence_of[i])

    scores: dict[str, float] = {}

    for word, frequency in term_freq.items():
        if word in fw or word in generic:
            scores[word] = 0.0
            continue

        document_frequency = len(docs_with_term[word])
        idf = (
            math.log(sentence_count / (1 + document_frequency)) + 1.0
            if sentence_count > 1
            else 1.0
        )
        scores[word] = frequency * idf

    if not scores:
        return [tok.text for tok in tokens if not tok.is_punct]

    positive_scores = sorted(
        score for score in scores.values() if score > 0
    )
    threshold = (
        positive_scores[len(positive_scores) // 2]
        if positive_scores
        else 0
    )

    keep = [False] * n
    sentence_has_keep = [False] * sentence_count

    for i, tok in enumerate(tokens):
        if tok.is_punct:
            continue

        if is_proper[i]:
            keep[i] = True
            sentence_has_keep[sentence_of[i]] = True
            continue

        if _is_number(tok.text):
            keep[i] = True
            sentence_has_keep[sentence_of[i]] = True
            continue

        key = keys[i]

        if key is None:
            continue

        score = scores.get(key, 0)

        if score > 0 and score >= threshold:
            keep[i] = True
            sentence_has_keep[sentence_of[i]] = True

    # Safety floor: a sentence that scored nothing above threshold still keeps
    # its single highest-scoring word.
    for sentence_index in range(sentence_count):
        if sentence_has_keep[sentence_index]:
            continue

        best_index = -1
        best_score = -1.0

        for i, tok in enumerate(tokens):
            if (
                sentence_of[i] != sentence_index
                or tok.is_punct
                or is_proper[i]
                or _is_number(tok.text)
            ):
                continue

            key = keys[i]

            if key is None:
                continue

            score = scores.get(key, 0)

            if score > best_score:
                best_score = score
                best_index = i

        if best_index >= 0:
            keep[best_index] = True

    out: list[str] = []

    for i, tok in enumerate(tokens):
        if not keep[i]:
            continue

        if is_proper[i] or _is_number(tok.text):
            out.append(tok.text)
            continue

        key = keys[i]

        if key is not None:
            out.append(key)

    return out


def _filter_syntactic(
    tokens: list[_Token],
    fw: frozenset[str],
    lemmas: dict[str, str],
    proper_nouns: frozenset[str],
    iso3: str,
    generic: frozenset[str],
    pos_tags: dict[str, str],
) -> list[str]:
    """Rule-based syntactic pruning (ported from Caveman C# 1.4.1).

    Same content-word filtering as AGGRESSIVE, except a function word survives when
    it is grammatical glue directly touching a word that itself survives — a
    determiner right in front of its noun — so the result reads as a terse but
    grammatical sentence instead of a keyword bag. Kept function words are never
    lemmatised.

    When pos_tags is non-empty, a leading hedging/matrix clause ("I kindly ask you
    to...", "vorrei che tu...") is additionally elided in favour of the sentence's
    last verb — gated on real POS evidence (a first attempt without it broke on
    verb/preposition homographs, e.g. Italian "entro" = "by/within" vs. "I enter")
    and restricted to only fire when every token between two candidate verbs is
    grammatical glue or a descriptive modifier, never a real content noun, so
    coordinated clauses ("I bought bread and ate cake") are never mistaken for a
    hedge clause and gutted. Proper nouns are never elided. Without POS data for the
    language, elision is a no-op.
    """
    group = _lang_group(iso3)
    is_proper = _detect_proper_nouns(tokens, iso3, proper_nouns)
    n = len(tokens)

    def next_survives(j: int) -> bool:
        if j >= n or tokens[j].is_punct:
            return False

        if is_proper[j]:
            return True

        if _is_number(tokens[j].text):
            return True

        j_lower = tokens[j].text.lower()

        if j_lower in fw:
            return False

        j_norm = _lemma_or_lower(tokens[j].text, lemmas, pos_tags)

        if j_norm in fw or j_norm in generic:
            return False

        if _is_descriptive(j_norm, group):
            return False

        return True

    def is_glue_or_modifier(i: int) -> bool:
        if tokens[i].is_punct or is_proper[i]:
            return True
        lower = tokens[i].text.lower()
        norm = _lemma_or_lower(tokens[i].text, lemmas, pos_tags)
        return lower in fw or norm in fw or _is_descriptive(norm, group)

    # elided[i]: inside a leading hedge/matrix clause the POS-gated pass chose to drop
    # wholesale (proper nouns are exempted and flow through normal handling).
    elided = [False] * n
    if pos_tags:
        clause_start = 0
        for i in range(n + 1):
            if i < n and not (tokens[i].is_punct and tokens[i].text in _SENTENCE_ENDERS):
                continue
            s, e = clause_start, i
            clause_start = i + 1

            verb_idx = [
                k for k in range(s, e)
                if not tokens[k].is_punct and not is_proper[k]
                and pos_tags.get(tokens[k].text.lower()) == "VERB"
            ]
            if len(verb_idx) < 2:
                continue

            gaps_clear = True
            for a, b in zip(verb_idx, verb_idx[1:]):
                for j in range(a + 1, b):
                    if not is_glue_or_modifier(j):
                        gaps_clear = False
                        break
                if not gaps_clear:
                    break

            if gaps_clear:
                for j in range(s, verb_idx[-1]):
                    if not is_proper[j]:
                        elided[j] = True

    # is_func[i]: tokens kept purely as grammatical glue keep their surface form
    # verbatim in the output pass below, never run through lemmatisation.
    keep = [False] * n
    is_func = [False] * n

    for i, tok in enumerate(tokens):
        if tok.is_punct or elided[i]:
            continue

        if is_proper[i]:
            keep[i] = True
            continue

        if _is_number(tok.text):
            keep[i] = True
            continue

        lower = tok.text.lower()
        normalized = _lemma_or_lower(tok.text, lemmas, pos_tags)

        if lower in fw or normalized in fw:
            keep[i] = next_survives(i + 1)
            is_func[i] = True
            continue

        if normalized in generic:
            continue

        if _is_descriptive(normalized, group):
            continue

        keep[i] = True

    # Safety floor per sentence: never elide a whole sentence to nothing.
    sentence_of, sentence_count = _sentence_index_of(tokens)
    sentence_has_keep = [False] * sentence_count
    for i in range(n):
        if keep[i]:
            sentence_has_keep[sentence_of[i]] = True
    for i, tok in enumerate(tokens):
        if sentence_has_keep[sentence_of[i]] or tok.is_punct:
            continue
        keep[i] = True
        sentence_has_keep[sentence_of[i]] = True

    out = []
    for i, tok in enumerate(tokens):
        if not keep[i]:
            continue
        if is_proper[i] or is_func[i]:
            out.append(tok.text)
            continue
        out.append(_lemma_or_lower(tok.text, lemmas, pos_tags))
    return out


def _apply_custom(
    tokens: list[_Token],
    fw: frozenset[str],
    f: CompressionFilter,
) -> list[str]:
    out = []
    for tok in tokens:
        if tok.is_punct and f.remove and "PUNCT" in f.remove:
            continue
        if f.keep_only is not None:
            cat = _categorize(tok.text, fw)
            if cat not in f.keep_only:
                continue
        elif f.remove and "FUNC" in f.remove:
            if tok.text.lower() in fw:
                continue
        if f.custom_predicate is not None and not f.custom_predicate(tok.text):
            continue
        out.append(tok.text)
    return out
